name: release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    - name: Build
      run: |
        go mod tidy
        go build -o influxdbv2-database-plugin cmd/influxdbv2-database-plugin/main.go
    - name: Calculate SHA256 checksum
      run: |
        sha256sum influxdbv2-database-plugin | cut -d ' ' -f1 > influxdbv2-database-plugin.sha256
    - name: Create GitHub release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: influxdbv2-database-plugin
        asset_name: influxdbv2-database-plugin
        asset_content_type: application/gzip
    - name: Upload checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: influxdbv2-database-plugin.sha256
        asset_name: influxdbv2-database-plugin.sha256
        asset_content_type: text/plain
